TOKEN_URL = "meu_link_token"
CLIENT_ID_ELETRO = "meu_client_id"
CLIENT_SECRET_ELETRO = "meu_client_secret"
CONSULTA_URL = "meu_link_de_consulta"

TOKEN_FILE = "token.txt"
MAX_RETRIES = 3
PRODUCAO = "link_api_base_producao"

API_SABIUM="link_apo"
USERSABIUM = "user"
PASSWORDSABIUM = "password"